//! chat_module — a Rust Logos Module (cdylib authoring model).
//!
//! Wraps libchat for the e2e-encrypted chat protocol and reaches the network
//! via delivery_module over IPC. The module-impl C ABI (`logos_module_*`
//! exports, the `ChatModule` trait, dispatch) is generated from
//! `chat_module.lidl` by logos-lidl-gen and `include!`d below from
//! `generated/provider_gen.rs`; the matching Qt plugin glue is generated by
//! logos-module-builder. The contract consumers call is `chat_module.lidl`;
//! we implement it here.
//!
//! Thread safety. State is split across two locks (see [`module`]): the client
//! lock guards the libchat `ChatClient` (held across crypto); the display lock
//! guards the conversation history, so the read methods never wait on the slow
//! client work. The operations below are safe to call from any thread.
//!
//! `init` imposes no thread-affinity requirement: the SDK makes calls into
//! delivery_module (event subscription, publish) thread-safe regardless of the
//! caller's thread.
//!
//! Return conventions. Status-bearing methods return `result`, surfaced here as
//! `Result<serde_json::Value, String>`: `Ok(value)` carries any payload (a
//! conversation id or `Null`), `Err(message)` a human-readable reason.
//! Collection getters return `serde_json::Value` (a JSON array/object);
//! `get_installation_name`/`get_address`/`get_log_path` return a plain string,
//! empty when not initialised.
//!
//! Events reach consumers over the lp_* IPC channel: the operations below call
//! the generated `emit_*` functions (see the included scaffold), which the host
//! marshals onto the Qt thread and republishes as IPC events.
//!
//! Security. The identity store opened by `init` is keyed from the
//! host-assigned instance persistence path: obfuscated, not protected.
//! Passphrase UX is planned.

mod actions;
mod delivery;
mod inbound;
mod logging;
mod module;
mod panic_hook;
mod persistence;

use serde_json::Value;

use module::{module, InstallOutcome};

// The module-impl C ABI scaffold generated from chat_module.lidl: the
// `ChatModule` trait, `RustModuleContext`, `install`, dispatch, the `emit_*`
// event emitters, and the `#[no_mangle] logos_module_*` exports the Qt glue
// drives. Machine output — not hand-maintained — so it lives in its own module
// that opts out of clippy and rustc lints; we lint the module code, not this.
// (`include!` already keeps it out of rustfmt, which does not descend into it.)
mod generated {
    #![allow(warnings)]
    #![allow(clippy::all)]
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/generated/provider_gen.rs"
    ));
}
pub(crate) use generated::*;

/// Error string for the unreachable lock-poison case. The process runs under
/// `panic = "abort"`, so a panic dies before it can poison the mutex; the arm
/// exists only to satisfy the `result` return type.
const ERR_LOCK_POISONED: &str = "internal error: module lock poisoned";

/// The `ChatConfig` record `init` received, as the object its fields are read
/// out of.
///
/// Two shapes arrive. A caller with a generated client sends an object. A caller
/// using `logoscore call` sends the object's JSON *text*, because the CLI coerces
/// an argument to a bool, a number or a string and never to an object — so a
/// record parameter reaches a module as a string or not at all.
fn chat_config(argument: Value) -> Value {
    let Value::String(text) = &argument else {
        return argument;
    };
    serde_json::from_str(text).unwrap_or_else(|_| {
        // Said out loud: the argument before the record existed was the preset
        // itself, so the alternative is joining the wrong delivery network in
        // silence.
        eprintln!(
            "chat_module init: {text:?} is not a ChatConfig record; pass the \
             record, or its JSON text. Every setting takes its default."
        );
        Value::Null
    })
}

/// One field of a [`chat_config`] record.
///
/// The record materialises untyped — today's codegen has no generated struct for
/// a record in parameter position — so every field is read out by hand and every
/// one is optional. An empty string is what an absent field, a field of the wrong
/// type, and a caller who sent no record at all all look like; each field's own
/// default covers it.
fn config_field<'a>(config: &'a Value, name: &str) -> &'a str {
    config.get(name).and_then(Value::as_str).unwrap_or_default()
}

/// The `ChatModule` contract implementation. Stateless: all module state lives
/// in the [`module`] singleton and the display lock, so every method delegates
/// to `actions` (which own their locking) and `&mut self` is unused.
#[derive(Default)]
struct ChatModuleImpl;

impl ChatModule for ChatModuleImpl {
    fn init(&mut self, config: Value) -> Result<Value, String> {
        panic_hook::install_once();
        let config = chat_config(config);
        logging::install_once(config_field(&config, "log_level"));

        let preset = match config_field(&config, "delivery_preset") {
            "" => "logos.test",
            named => named,
        };

        match module().install_with(actions::initialize) {
            Err(_) => Err(ERR_LOCK_POISONED.to_string()),
            Ok(Ok(InstallOutcome::Installed)) => {
                tracing::info!("init: state installed, joining delivery preset {preset}");
                // State is installed and the module lock is released; only now
                // bootstrap delivery, so its async completion callbacks acquire
                // a free lock instead of re-entering the one init holds.
                actions::start_delivery_bootstrap(preset);
                Ok(Value::Null)
            }
            Ok(Ok(InstallOutcome::AlreadyInstalled)) => {
                tracing::warn!(
                    "init: already initialised; any new arguments are ignored, \
                     call shutdown() first to reconfigure"
                );
                Ok(Value::Null)
            }
            Ok(Err(e)) => {
                tracing::error!("init: {e}");
                Err(e.to_string())
            }
        }
    }

    fn shutdown(&mut self) -> Result<Value, String> {
        // Take the module out of the lock before joining the inbound thread —
        // the worker may try to re-acquire the mutex to handle a pending event,
        // and holding it during `join` would deadlock.
        let taken = module().take().map_err(|_| ERR_LOCK_POISONED.to_string())?;
        if let Some(ms) = taken {
            actions::shutdown(ms);
        }
        Ok(Value::Null)
    }

    fn get_log_path(&mut self) -> String {
        logging::log_path()
    }

    /// Touches no state and takes no lock: a probe that could block would report
    /// a busy module as a dead one, and the process answering is the whole
    /// answer. Deliberately silent, since a caller polls this.
    fn health(&mut self) -> bool {
        true
    }

    fn get_installation_name(&mut self) -> String {
        actions::installation_name()
    }

    fn set_installation_name(&mut self, name: String) -> Result<Value, String> {
        actions::set_installation_name(&name)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn get_address(&mut self) -> String {
        actions::get_address()
    }

    fn create_conversation(&mut self, peer_address: String) -> Result<Value, String> {
        actions::create_conversation(&peer_address)
            .map(Value::String)
            .map_err(|e| e.to_string())
    }

    fn create_group_conversation(&mut self, name: String, desc: String) -> Result<Value, String> {
        actions::create_group_conversation(&name, &desc)
            .map(Value::String)
            .map_err(|e| e.to_string())
    }

    fn add_group_member(
        &mut self,
        convo_id: String,
        peer_address: String,
    ) -> Result<Value, String> {
        actions::add_group_member(&convo_id, &peer_address)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn list_conversations(&mut self) -> Value {
        actions::list_conversations()
    }

    fn get_messages(&mut self, convo_id: String) -> Value {
        actions::get_messages(&convo_id)
    }

    fn list_group_members(&mut self, convo_id: String) -> Value {
        actions::list_group_members(&convo_id)
    }

    fn send_message(&mut self, convo_id: String, content: String) -> Result<Value, String> {
        actions::send_message(&convo_id, &content)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn set_conversation_nickname(
        &mut self,
        convo_id: String,
        nickname: String,
    ) -> Result<Value, String> {
        actions::set_conversation_nickname(&convo_id, &nickname)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn delete_conversation(&mut self, convo_id: String) -> Result<Value, String> {
        actions::delete_conversation(&convo_id)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn status(&mut self) -> Value {
        actions::status()
    }
}

/// Install hook resolved by the generated scaffold (invoked lazily on first
/// dispatch); wires `ChatModuleImpl` as the module implementation.
#[no_mangle]
pub extern "Rust" fn logos_module_install() {
    install::<ChatModuleImpl>();
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A generated client sends the record as an object.
    #[test]
    fn a_record_is_read_field_by_field() {
        let config = chat_config(serde_json::json!({
            "delivery_preset": "logos.test",
            "log_level": "debug",
        }));

        assert_eq!(config_field(&config, "delivery_preset"), "logos.test");
        assert_eq!(config_field(&config, "log_level"), "debug");
    }

    /// `logoscore call` can only send the record as text, so the text is the
    /// record.
    #[test]
    fn the_records_json_text_is_the_record() {
        let config = chat_config(Value::String(
            r#"{"delivery_preset":"logos.test"}"#.to_string(),
        ));

        assert_eq!(config_field(&config, "delivery_preset"), "logos.test");
    }

    /// Every field is optional, so a caller may configure one setting and leave
    /// the rest alone.
    #[test]
    fn an_absent_field_reads_empty() {
        let config = chat_config(serde_json::json!({ "log_level": "trace" }));

        assert_eq!(config_field(&config, "delivery_preset"), "");
        assert_eq!(config_field(&config, "log_level"), "trace");
    }

    /// What a caller from before the record sends: the preset on its own. It is
    /// not a record, so it configures nothing — but it must not take the module
    /// down on the way to finding that out.
    #[test]
    fn an_argument_that_is_no_record_configures_nothing() {
        for argument in [
            Value::String("logos.test".to_string()),
            Value::Null,
            serde_json::json!(3),
            serde_json::json!(["logos.test"]),
        ] {
            let config = chat_config(argument);

            assert_eq!(config_field(&config, "delivery_preset"), "");
            assert_eq!(config_field(&config, "log_level"), "");
        }
    }
}
