// Stub header for liblogoschat - provides the same declarations as the real
// header (generated by the logos-chat build) so that chat_module_plugin.cpp
// compiles during unit tests without the real library.

#ifndef LIBLOGOSCHAT_H
#define LIBLOGOSCHAT_H

#include <stddef.h>

#define RET_OK  0
#define RET_ERR 1

#ifdef __cplusplus
extern "C" {
#endif

typedef void (*chat_callback)(int callerRet, const char* msg, size_t len, void* userData);

// Create a new chat client from a JSON config string.
// Returns a non-null context pointer on success; null on failure.
void* chat_new(const char* cfg, chat_callback cb, void* userData);

// Start the chat client. Callback called on completion.
int chat_start(void* ctx, chat_callback cb, void* userData);

// Stop the chat client. Callback called on completion.
int chat_stop(void* ctx, chat_callback cb, void* userData);

// Destroy the chat client context. Callback called on completion.
int chat_destroy(void* ctx, chat_callback cb, void* userData);

// Register a persistent event callback for async push events.
void set_event_callback(void* ctx, chat_callback cb, void* userData);

// Retrieve the local client's unique identifier. Callback returns the ID string.
int chat_get_id(void* ctx, chat_callback cb, void* userData);

// Retrieve all conversations the local client participates in.
int chat_list_conversations(void* ctx, chat_callback cb, void* userData);

// Retrieve a single conversation by its identifier.
int chat_get_conversation(void* ctx, chat_callback cb, void* userData, const char* convoId);

// Start a new private (1-to-1) conversation with a remote contact.
int chat_new_private_conversation(void* ctx, chat_callback cb, void* userData, const char* introBundleStr, const char* contentHex);

// Send a message to an existing conversation.
int chat_send_message(void* ctx, chat_callback cb, void* userData, const char* convoId, const char* contentHex);

// Retrieve the local client's identity information.
int chat_get_identity(void* ctx, chat_callback cb, void* userData);

// Create a new introduction bundle for sharing with other users.
int chat_create_intro_bundle(void* ctx, chat_callback cb, void* userData);

#ifdef __cplusplus
}
#endif

#endif /* LIBLOGOSCHAT_H */
